# Generated by Django 2.1.5 on 2019-02-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('editora', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=150, null=True)),
                ('ano', models.IntegerField(default=0)),
                ('quantidade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
