# Generated by Django 2.1.5 on 2019-04-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_emprestimo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
