# Generated by Django 2.1.5 on 2019-04-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_aluno_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.CharField(default='ativo', max_length=10),
        ),
    ]
