# Generated by Django 2.1.5 on 2019-04-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_auto_20190417_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='valor_debito',
            field=models.FloatField(null=True),
        ),
    ]
