# Generated by Django 2.1.5 on 2019-04-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='logado',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
